SozlukProje/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SozlukProje.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());

        public ActionResult Index()
        {
            var categoryValues = categoryManager.GetList();
            return View(categoryValues);
        }

        [HttpGet]
        public ActionResult AddCategory()
		{
            return View();
		}

        [HttpPost]
        public ActionResult AddCategory(Category p)
		{
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(p);
			if (results.IsValid)
			{
                categoryManager.CategoryAdd(p);
                return RedirectToAction("Index");
			}
			else
			{
				foreach (var item in results.Errors)
				{
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
				}
			}
            return View();
		}

        public ActionResult DeleteCategory (int id)
		{
            var categoryValue = categoryManager.GetById(id);
            categoryManager.CategoryDelete(categoryValue);
            return RedirectToAction("Index");
		}

        [HttpGet]
        public ActionResult UpdateCategory(int id)
		{
            var categoryValue = categoryManager.GetById(id);
            categoryManager.CategoryUpdate(categoryValue);
            return View(categoryValue);
		}

        [HttpPost]
        public ActionResult UpdateCategory(Category p)
        {
            categoryManager.CategoryUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

SozlukProje/Views/AdminCategory/AddCategory.cshtml
@model  EntityLayer.Concrete.Category

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1 style="text-align:center">KATEGORİ EKLE</h1>
<br />
@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br />
        <br />
        @Html.Label("Açıklamayı Yazınız")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br />
        <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

SozlukProje/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>KATEGORİ ADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>BAŞLIKLAR</th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
        <th>@item.CategoryId</th>
        <td>@item.CategoryName</td>
        <td><a href="/AdminCategory/DeleteCategory/@item.CategoryId" class="btn btn-danger">SİL</a></td>
        <td><a href="/AdminCategory/UpdateCategory/@item.CategoryId" class="btn btn-warning">GÜNCELLE</a></td>
        <td><a href="#" class="btn btn-primary">BAŞLIKLAR</a></td>
</tr>
    }

</table>
<a href="/AdminCategory/AddCategory" class="btn btn-success">Yeni Kategori</a>

SozlukProje/Views/AdminCategory/UpdateCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "UpdateCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>KATEGORİ GÜNCELLEME</h2>
@using (Html.BeginForm("UpdateCategory", "AdminCategory", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Kategori ID")
    @Html.TextBoxFor(x => x.CategoryId, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori Adı")
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori Açıklaması")
    @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
}