SozlukProje/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SozlukProje.Controllers
{
    public class HeadingController : Controller
    {
        // GET: Heading
        HeadingManager headingManager = new HeadingManager(new EfHeadingDal());
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        WriterManager writerManager = new WriterManager(new EfWriterDal());
        public ActionResult Index()
        {
            
            var headingValues = headingManager.GetList();
            return View(headingValues);
        }

        [HttpGet]
        public ActionResult AddHeading()
		{

            List<SelectListItem> valueCategory = (from x in categoryManager.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text=x.CategoryName,
                                                      Value=x.CategoryId.ToString()
                                                  }).ToList();
            ViewBag.valueCategory = valueCategory;

            List<SelectListItem> valueWriter = (from x in writerManager.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.WriterName+" "+x.WriterSurName,
                                                      Value = x.WriterId.ToString()
                                                  }).ToList();
            ViewBag.valueWriter = valueWriter;
            return View();
		}

        [HttpPost]
        public ActionResult AddHeading(Heading heading)
        {
            heading.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            headingManager.HeadingAdd(heading);
            return RedirectToAction("Index");
        }

        public ActionResult GetContentByHeading()
		{
            return View();
        }
    }
}

SozlukProje/Views/Heading/AddHeading.cshtml
@model  EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Başlık Oluşturma</h1>
<br />
@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlığın Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Başlık Kategorisi")
        @Html.DropDownListFor(x=>x.CategoryId,(List<SelectListItem>)ViewBag.valueCategory,new { @class = "form-control" })
        <br />
        @Html.Label("Yazar")
        @Html.DropDownListFor(x=>x.WriterId,(List<SelectListItem>)ViewBag.valueWriter,new { @class="form-control"})
        <br />
        <button class="btn btn-info">Başlığı Oluştur</button>
    </div>
}

SozlukProje/Views/Heading/GetContentByHeading.cshtml
@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            <div class="time-label">
                                <span class="bg-success">Tarih</span>
                            </div>
                            <!-- /.timeline-label -->
                            <!-- timeline item -->
                            <div>
                                <i class="fas fa-comment bg-yellow"></i>
                                <div class="timeline-item">
                                    <h3 class="timeline-header"><a href="#">Test</a> Deneme</h3>
                                    <div class="timeline-body">
                                        İçerik
                                    </div>
                                </div>
                            </div>
                            <!-- END timeline item -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

SozlukProje/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model  List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{string color = ""; }

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">


        <!-- Content Wrapper. Contains page content -->
            <!-- Content Header (Page header) -->

            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Başlık İşlemleri</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <table class="table table-striped projects">
                            <thead>
                                <tr>
                                    <th style="width: 1%">
                                        Başlık ID
                                    </th>
                                    <th style="width: 20%">
                                        Başlık Adı
                                    </th>
                                    <th style="width: 30%">
                                        Başlığı Oluşturan Yazar
                                    </th>
                                    <th style="width: 8%" class="text-center">
                                        Kategori
                                    </th>
                                    <th style="width: 20%">
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    if (item.Category.CategoryId==1)
                                    {
                                        color = "badge badge-success";
                                    }
                                    else if (item.Category.CategoryId == 2)
                                    {
                                        color = "badge badge-warning";
                                    }
                                    else if (item.Category.CategoryId == 3)
                                    {
                                        color = "badge badge-danger";
                                    }
                                    else if (item.Category.CategoryId == 4)
                                    {
                                        color = "badge badge-info";
                                    }
                                    else if (item.Category.CategoryId == 5)
                                    {
                                        color = "badge badge-dark";
                                    }
                                    else if (item.Category.CategoryId == 6)
                                    {
                                        color = "badge badge-pill";
                                    }
                                    else if (item.Category.CategoryId == 7)
                                    {
                                        color = "badge badge-primary";
                                    }
                                    else if (item.Category.CategoryId == 8)
                                    {
                                        color = "badge badge-secondary";
                                    }
                                    else
                                    {
                                        color = "badge badge-light";
                                    }

                                <tr>
                                    <td>
                                        @item.HeadingId
                                    </td>
                                    <td>
                                        <a>
                                            @item.HeadingName
                                        </a>
                                        <br />
                                        <small>
                                            @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"));
                                        </small>
                                    </td>
                                    <td>
                                        <ul class="list-inline">
                                            <li class="list-inline-item">
                                                <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                                <p><b>@item.Writer.WriterName @item.Writer.WriterSurName</b></p>
                                            </li>
                                          
                                        </ul>
                                    </td>
                                    
                                    <td class="project-state">
                                        <span class="@color">@item.Category.CategoryName</span>
                                    </td>
                                    <td class="project-actions text-right">
                                        <a class="btn btn-primary btn-sm" href="/Content/GetContentByHeading/@item.HeadingId">
                                            <i class="fas fa-folder">
                                            </i>
                                            Gönderiler
                                        </a>
                                        <a class="btn btn-info btn-sm" href="#">
                                            <i class="fas fa-pencil-alt">
                                            </i>
                                            Düzenle
                                        </a>
                                        <a class="btn btn-danger btn-sm" href="#">
                                            <i class="fas fa-trash">
                                            </i>
                                            Sil
                                        </a>
                                    </td>
                                </tr>
                                }
                           
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </section>

</body>
</html>
<a href="/Heading/AddHeading/" class="btn btn-primary">Yeni Başlık Oluştur</a>


@*<h2>BAŞLIKLAR</h2>
    <br />
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>BAŞLIK ADI</th>
            <th>BAŞLIK TARİHİ</th>
            <th>BAŞLIK KATEGORİSİ</th>
            <th>BAŞLIĞI OLUŞTURAN YAZAR</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.HeadingId</td>
                <td>@item.HeadingName</td>
                <td>@item.HeadingDate</td>
                <td>@item.Category.CategoryName</td>
                <td>@item.Writer.WriterName @item.Writer.WriterSurName</td>
            </tr>
        }
        </table>
    <br />
    <a href="/Heading/AddHeading" class="btn btn-info">Yeni Başlık Oluştur</a>*@